#!/bin/bash
GHIDRA_INSTALL_DIR="~/installs/apps/ghidra_9.1.1_PUBLIC"
GHIDRA_SCRIPTS_DIR="~/projects/hacking/ghidrascripts"
binary="$1"
script_name="$2"
shift 2
eval "$GHIDRA_INSTALL_DIR/support/analyzeHeadless" /tmp/ ProjectName  -import "$binary" -deleteProject -scriptPath "$GHIDRA_SCRIPTS_DIR" -postScript "$script_name" "$@" 2> /dev/null | grep "INFO  $script_name> " | sed "s/^INFO  $script_name> \(.*\) (GhidraScript)/\1/"
